/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jk_5_nailed_mumblelink_Mumble */

#ifndef _Included_jk_5_nailed_mumblelink_Mumble
#define _Included_jk_5_nailed_mumblelink_Mumble
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jk_5_nailed_mumblelink_Mumble
 * Method:    update
 * Signature: ([F[F[FLjava/lang/String;Ljava/lang/String;[F[F[FLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jk_15_nailed_mumblelink_Mumble_update
  (JNIEnv *, jobject, jfloatArray, jfloatArray, jfloatArray, jstring, jstring, jfloatArray, jfloatArray, jfloatArray, jstring, jstring);

/*
 * Class:     jk_5_nailed_mumblelink_Mumble
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jk_15_nailed_mumblelink_Mumble_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
