/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jk_5_nailed_encryption_NativeCipherImpl */

#ifndef _Included_jk_5_nailed_encryption_NativeCipherImpl
#define _Included_jk_5_nailed_encryption_NativeCipherImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jk_5_nailed_encryption_NativeCipherImpl
 * Method:    init
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_jk_15_nailed_encryption_NativeCipherImpl_init
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     jk_5_nailed_encryption_NativeCipherImpl
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jk_15_nailed_encryption_NativeCipherImpl_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jk_5_nailed_encryption_NativeCipherImpl
 * Method:    cipher
 * Signature: (ZJ[BJJJ)V
 */
JNIEXPORT void JNICALL Java_jk_15_nailed_encryption_NativeCipherImpl_cipher
  (JNIEnv *, jobject, jboolean, jlong, jbyteArray, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
